### ISSUE TITLE
Security update pt 1

### ISSUE THREAD

**Issue by GiltedShadow** [thomashailey/legendary-spork#20]
will be working in Employee.java

- [ ] adding getters, setters, and constructors
- [ ] adding comments describing how code works
- [ ] starting documentation on how-to and what this part of the project does

### TODO ###
- [ ] what needs to be changed to interact properly with the g/s/c within the main code

**Comment by GiltedShadow** [comment]
I'm pretty sure this'll require quite a bit of a rewrite since almost all of the variables are just stored within the SQL database and prepared statements but it'll be a good thing to work through
